# Workflow for detecting secrets and sensitive information in the repository using Gitleaks.
name: Secret Detection

on:
  workflow_call:

jobs:
  gitleaks:
    name: Gitleaks (Secrets)
    runs-on: ubuntu-latest
    permissions:
      contents: read # Permission to read repository contents
      pull-requests: write # Permission for posting comments
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Required to scan git diff/history

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        continue-on-error: true  # Temporarily continue on error during testing phase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
